added new workflow to test AM 3.5.1 Dockerfile fix, so to replay docker release

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1772,7 +1772,6 @@ jobs:
               echo "# --->>> THIS IS A DRY RUN : SKIPPING DOCKER PUSH"
             fi;
 
-
   build_n_push_am_ee_v3_ui_job:
     machine:
       image: 'ubuntu-1604:201903-01'
@@ -1915,6 +1914,162 @@ jobs:
               else
                 echo "# --->>> THIS IS A DRY RUN : THIS IS NOT A LATEST RELEASE, SO WILL DOCKER PUSH ONLY [${RELEASE_VERSION}]=[${RELEASE_VERSION_MAJOR}.${RELEASE_VERSION_MINOR}.${RELEASE_VERSION_PATCH}]"
                 docker push "graviteeio/am-management-ui:${RELEASE_VERSION}-ee"
+                if [ "$TAG_LATEST_SUPPORT" == "true" ]; then
+                    echo "Gravitee Containers :  Docker tags, Releasing Docker images as latest support"
+                    docker push "graviteeio/am-management-ui:${RELEASE_VERSION_MAJOR}.${RELEASE_VERSION_MINOR}-ee"
+                else
+                    echo "Gravitee Containers :  Docker tags, Releasing Docker images as NON-latest"
+                fi
+              fi;
+            else
+              echo "# --->>> THIS IS A DRY RUN : SKIPPING DOCKER PUSH"
+            fi;
+
+  build_n_push_am_ee_v351_ui_job:
+    machine:
+      image: 'ubuntu-1604:201903-01'
+      resource_class: large
+      docker_layer_caching: true    # default - false # requires a Circle CI plan that includes [Docker layer caching feature]
+    environment:
+      DRY_RUN: << pipeline.parameters.dry_run >>
+      TAG_LATEST: << pipeline.parameters.tag_latest >>
+      TAG_LATEST_SUPPORT: << pipeline.parameters.tag_latest_support >>
+      PRUNE_IT_ALL: << pipeline.parameters.prune >>
+      GRAVITEEIO_VERSION: << pipeline.parameters.graviteeio_version >>
+      SECRETHUB_ORG: << pipeline.parameters.secrethub_org >>
+      SECRETHUB_REPO: << pipeline.parameters.secrethub_repo >>
+    steps:
+      - checkout
+      - secrethub/install
+      - gravitee/git_config:
+          secrethub_org: << pipeline.parameters.secrethub_org >>
+          secrethub_repo: << pipeline.parameters.secrethub_repo >>
+      - run:
+          name: "Gravitee AM EE v3 Management UI: Check Environment"
+          command: |
+            pwd
+            ls -allh
+            export OPS_HOME=$(pwd)
+            export RELEASE_VERSION=$GRAVITEEIO_VERSION
+            export RELEASE_VERSION_MAJOR=$(echo "$GRAVITEEIO_VERSION" | awk -F '.' '{print $1}')
+            export RELEASE_VERSION_MINOR=$(echo "$GRAVITEEIO_VERSION" | awk -F '.' '{print $2}')
+            export RELEASE_VERSION_PATCH=$(echo "$GRAVITEEIO_VERSION" | awk -F '.' '{print $3}')
+            echo " "
+            echo " [--------------------------------------------------------------------------------] "
+            echo " [--------------------------------------------------------------------------------] "
+            echo " [--------------------------------------------------------------------------------] "
+            echo " [--------------------------------------------------------------------------------] "
+            echo "                            FOR THE DOCKER RELEASE : "
+            echo "                                "
+            echo " [--------------------------------------------------------------------------------] "
+            echo "      RELEASE_VERSION=[${RELEASE_VERSION}]"
+            echo "      RELEASE_VERSION_MAJOR=[${RELEASE_VERSION_MAJOR}]"
+            echo "      RELEASE_VERSION_MINOR=[${RELEASE_VERSION_MINOR}]"
+            echo "      RELEASE_VERSION_PATCH=[${RELEASE_VERSION_PATCH}]"
+            echo " [--------------------------------------------------------------------------------] "
+            echo " [--------------------------------------------------------------------------------] "
+            echo " [--------------------------------------------------------------------------------] "
+            if ! [ "${RELEASE_VERSION_MAJOR}" == "3" ]; then
+              echo "The [${RELEASE_VERSION}] version is not a Gravitee V3 Generation version"
+              exit 3
+            fi;
+      - run:
+          name: "Prune"
+          command: |
+            if [ "$PRUNE_IT_ALL" == "true" ]; then
+              echo "Pruning all Docker images"
+              docker system prune -f --all
+            else
+              echo "Skipped Pruning all Docker images "
+            fi;
+      - run:
+          name: "If Dry run, build Community Edition Container Images"
+          command: |
+            echo " [--------------------------------------------------------------------------------] "
+            echo "    Gravitee AM Entreprise Edition UI Image is built FROM Community Edition Image"
+            echo "    If this job is run with DRY RUN mode on, Community Edition Image is not"
+            echo "     pushed to Dockerhub, so will be missing for "
+            echo "     Gravitee AM Entreprise Edition UI Image Container build"
+            echo " [--------------------------------------------------------------------------------] "
+
+            if [ "${DRY_RUN}" == "true" ]; then
+              echo "# --->>> THIS IS A DRY RUN : BUILDING COMMUNITY EDITION CONTAINER IMAGE"
+              # Testing if the git config properly configured SSH Agent
+              # echo "# ==> Testing if the git config properly configured SSH Agent"
+              # ssh -T git@github.com || true
+
+              pwd
+              ls -allh
+              export OPS_HOME=$(pwd)
+              export RELEASE_VERSION=$GRAVITEEIO_VERSION
+              export RELEASE_VERSION_MAJOR=$(echo "$GRAVITEEIO_VERSION" | awk -F '.' '{print $1}')
+              export RELEASE_VERSION_MINOR=$(echo "$GRAVITEEIO_VERSION" | awk -F '.' '{print $2}')
+              export RELEASE_VERSION_PATCH=$(echo "$GRAVITEEIO_VERSION" | awk -F '.' '{print $3}')
+              #
+              # Secure docker images tagging
+              if ! [ "${RELEASE_VERSION}" == "${RELEASE_VERSION_MAJOR}.${RELEASE_VERSION_MINOR}.${RELEASE_VERSION_PATCH}" ]; then
+                echo "[${RELEASE_VERSION}] and [${RELEASE_VERSION_MAJOR}.${RELEASE_VERSION_MINOR}.${RELEASE_VERSION_PATCH}] should be equal, and are not, stopping pipeline, debug and check pipeline."
+                exit 3
+              fi;
+              echo " Docker build: Gravitee Access Management version [${GRAVITEEIO_VERSION}]"
+              export DOCKER_WORKSHOP=$(mktemp -d -t "access_management-XXXXXXXXXX")
+              export GIT_SSH_URI=git@github.com:gravitee-io/graviteeio-access-management.git
+              cd ${OPS_HOME}
+              git clone ${GIT_SSH_URI} ${DOCKER_WORKSHOP}
+              cd ${DOCKER_WORKSHOP}
+              # git checkout "${GRAVITEEIO_VERSION}"
+              git checkout cicd/fix-351-dock-image
+              git checkout "${GRAVITEEIO_VERSION}"
+              cd ${OPS_HOME}
+              echo " [++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++] "
+              echo " [--------------------------------------------------------------------------------] "
+              echo "                            DOCKER BUILD GRAVITEE AM MANAGEMENT UI : "
+              echo " [--------------------------------------------------------------------------------] "
+              docker build -f ${DOCKER_WORKSHOP}/docker/management-ui/Dockerfile --build-arg GRAVITEEAM_VERSION=${RELEASE_VERSION} -t graviteeio/am-management-ui:${RELEASE_VERSION}-techopsfix ${DOCKER_WORKSHOP}/docker/management-ui/
+              docker images
+            else
+              echo "# --->>> THIS IS NOT A DRY RUN : SKIP BUILDING COMMUNITY EDITION CONTAINER IMAGE"
+            fi;
+
+      - run:
+          name: "Gravitee AM EE v3 Management UI: Build Container Image"
+          command: |
+            export RELEASE_VERSION=$GRAVITEEIO_VERSION
+            export RELEASE_VERSION_MAJOR=$(echo "$GRAVITEEIO_VERSION" | awk -F '.' '{print $1}')
+            export RELEASE_VERSION_MINOR=$(echo "$GRAVITEEIO_VERSION" | awk -F '.' '{print $2}')
+            export RELEASE_VERSION_PATCH=$(echo "$GRAVITEEIO_VERSION" | awk -F '.' '{print $3}')
+            echo ""
+            echo " [--------------------------------------------------------------------------------] "
+            echo "                            DOCKER BUILD GRAVITEE AM MANAGEMENT UI : "
+            echo " [--------------------------------------------------------------------------------] "
+            docker build -f ./enterprise/am/3.x/management-ui/Dockerfile --build-arg GRAVITEEIO_AM_VERSION=${RELEASE_VERSION}-techopsfix -t "graviteeio/am-management-ui:${RELEASE_VERSION}-ee-techopsfix" ./enterprise/am/3.x/management-ui/
+            docker tag "graviteeio/am-management-ui:${RELEASE_VERSION}-ee" "graviteeio/am-management-ui:${RELEASE_VERSION_MAJOR}-ee"
+            docker tag "graviteeio/am-management-ui:${RELEASE_VERSION}-ee" "graviteeio/am-management-ui:${RELEASE_VERSION_MAJOR}.${RELEASE_VERSION_MINOR}-ee"
+            docker images
+      - gravitee/docker_login:
+          secrethub_org: << pipeline.parameters.secrethub_org >>
+          secrethub_repo: << pipeline.parameters.secrethub_repo >>
+
+      - run:
+          name: "Gravitee AM EE v3 Management UI: Docker Push Container Image"
+          command: |
+            export RELEASE_VERSION=$GRAVITEEIO_VERSION
+            export RELEASE_VERSION_MAJOR=$(echo "$GRAVITEEIO_VERSION" | awk -F '.' '{print $1}')
+            export RELEASE_VERSION_MINOR=$(echo "$GRAVITEEIO_VERSION" | awk -F '.' '{print $2}')
+            export RELEASE_VERSION_PATCH=$(echo "$GRAVITEEIO_VERSION" | awk -F '.' '{print $3}')
+            if [ "${DRY_RUN}" == "false" ]; then
+              # --->>> NO IT IS NOT A DRY RUN
+              echo "# --->>> NO IT IS NOT A DRY RUN : GO DOCKER PUSH"
+              if [ "${TAG_LATEST}" == "true" ]; then
+                # --->>> NO IT IS NOT A DRY RUN
+                echo "# --->>> NO IT IS NOT A DRY RUN : THIS IS A LATEST RELEASE"
+                echo "This is just a fix for AM 3.5.1 release only : 3.5.1 is NOT A LATEST"
+                # docker push "graviteeio/am-management-ui:${RELEASE_VERSION_MAJOR}-ee"
+                # docker push "graviteeio/am-management-ui:${RELEASE_VERSION_MAJOR}.${RELEASE_VERSION_MINOR}-ee"
+                # docker push "graviteeio/am-management-ui:${RELEASE_VERSION}-ee"
+              else
+                echo "# --->>> THIS IS A DRY RUN : THIS IS NOT A LATEST RELEASE, SO WILL DOCKER PUSH ONLY [${RELEASE_VERSION}]=[${RELEASE_VERSION_MAJOR}.${RELEASE_VERSION_MINOR}.${RELEASE_VERSION_PATCH}]"
+                docker push "graviteeio/am-management-ui:${RELEASE_VERSION}-ee-techopsfix"
                 if [ "$TAG_LATEST_SUPPORT" == "true" ]; then
                     echo "Gravitee Containers :  Docker tags, Releasing Docker images as latest support"
                     docker push "graviteeio/am-management-ui:${RELEASE_VERSION_MAJOR}.${RELEASE_VERSION_MINOR}-ee"
@@ -2617,16 +2772,9 @@ workflows:
       - build_n_push_am_ce_v351_job:
           context: cicd-orchestrator
       # ---
-      # Builds and push AM v3 Entreprise Edition Images
-      - build_n_push_am_ee_v3_gateway_job:
-          context: cicd-orchestrator
-          requires:
-            - build_n_push_am_ce_v351_job
-      - build_n_push_am_ee_v3_api_job:
-          context: cicd-orchestrator
-          requires:
-            - build_n_push_am_ce_v351_job
-      - build_n_push_am_ee_v3_ui_job:
+      # Builds and push AM v3.5.1 Entreprise Edition Web UI Image
+      # - build_n_push_am_ee_v3_ui_job:
+      - build_n_push_am_ee_v351_ui_job:
           context: cicd-orchestrator
           requires:
             - build_n_push_am_ce_v351_job
